### ISSUE TITLE
AHK Image maker from YT

### ISSUE THREAD

**Issue by KRN-8** [Spawnova/ShinsImageScanClass#16]
Could you share that lil utility thingie that makes your Scan class THAT Much More comfortable to use ?
Honestly i kinda dont wanna install 1 thing i would only use for this and nothing much else, i DID have Gimp few years ago but i didnt use it soo when i got new PC i just kinda didnt bother XD

We are probably fine with some kind of early access pre-Alpha sloppy version of it too, just rly anything soo we can start enjoying it and give you some feedback (probably here on GitHub in a new Repo ?). 

Thanks,
your faithfull user(s) :-)

**Comment by Spawnova** [comment]
It's in the plans but kind of low priority, I don't have much free time anymore sadly, I do want to get around to it and when I do I will make a new repo for it, the problem is it was half programmed in c++ and compiled as a DLL and I don't really want to have people download a bunch of random DLLs required to run my scripts.

**Comment by KRN-8** [comment]
i get that, but if i get sth else (like gimp) i will end up with RNG libraries anyways (also takes waaay more space on my already overfilled disk)
welp, if i end up needing image search i will figure sth out i guess ;-(
(probably MS paint XD)
