### ISSUE TITLE
scan.GetPixel(x,y,1) is buggy with non int inputs ...

### ISSUE THREAD

**Issue by KRN-8** [Spawnova/ShinsImageScanClass#18]
when you give float input into `scan.GetPixel(x,y,1)` coordinates, you get garbage output, 
and there is nothing about (this) the function requiring integer input for coordinates in its description ... ;-((( !!!

i Just figured this out after around 3 days of bashing my head against the monitor in disbeleif on "why is it working this way but not that way ... grrr" XD

TLDR, You gotta Round or Ceiling or Floor the [x] and [y] before putting it into "GetPixel(...)" !
which is NOT the case for "All" other (mainly Draw... ) functions, ... hmm i wonder why XDD

**Comment by Spawnova** [comment]
You can think of the image class as a large array so something like `pixel[2.372635][231.023992]` would not work to get the pixel at position 2,231
However a lot of the functions are dllcalls which specify an int type, so they automatically get rounded down, the getpixel function on the other hand is not a dllcall and assumes ints

The 2 classes can be used together but they are not the same, the direct2d class can use actual floats since it's framework was designed around it, but the scan class is just simply an array of colors which require ints to access the pixel data

Either way, I'll update the class with flooring the ints for that function to keep similar behavior with the dllcall functions =)
