### ISSUE TITLE
Cached image

### ISSUE THREAD

**Issue by C00LM4N** [Spawnova/ShinsImageScanClass#28]
Hello! Was dealing with a strange issue where Image method was constantly finding the image even when game screen changed and the image is not visible anymore. Using SaveImage I've found that once your class gets game image first time it will get same one everytime until game restart (restarting script doesn't help). Seems to be a kind of caching in gdi lib? Maybe it's possible to flush it?

**Comment by Spawnova** [comment]
Hi, unfortunately this is an indication that the target window mode is not compatible with whatever process you are scanning
My class uses BitBlt to get the pixel data, but this is a very old windows function and it does not work with every program, if it's a game you can try changing the rendering method, otherwise the class would have to be setup in desktop mode by not specifying a window title

I can't fix this in ahk, but I do have plans to create a new version of the class using custom built dlls which will solve this issue, but it will be a while before it's all ready

**Comment by C00LM4N** [comment]
Thanks for your answer!
Looking forward into future releases.
